server:
  port: 9999
spring:
  application:
    name: spring-cloud-zuul
  cloud:
    zookeeper:
      ###当前服务注册到zookeeper注册中心
      connect-string: 111.231.116.214:2181
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 111.231.116.214
    # Redis服务器连接端口
    port: 6379
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000
    password: @
    banner:
      location: com\jason\server\banner.txt
zuul:
  routes:
    #标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    spring-cloud-user:
      #开启匹配前缀
      stripPrefix: false
      #为所有匹配增加前缀 否则访问路径需要 输入/spring-cloud-user/spring-cloud-user
      prefix: /spring-cloud-user
      #服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
      path: /spring-cloud-user/**
      #这里一定要是你Eureka注册中心的服务的名称，是所以这里配置serviceId因为跟eureka结合了，如果单独使用zuul,那么就必须写自己机器的IP了，
      #如url:http://localhost:8080/  这样的不好就是写死IP了，万一这IP挂了，这高可用性，服务注册那套东西就用不起来了
      #serviceId: spring-cloud-user
      url: http://${config.host:127.0.0.1}:${config.port:1001}
    spring-cloud-article:
      #开启匹配前缀
      stripPrefix: false
      #为所有匹配增加前缀 否则访问路径需要 输入/spring-cloud-article/spring-cloud-article
      prefix: /spring-cloud-article
      #服务映射的路径，通过这路径就可以从外部访问你的服务了，目的是为了不爆露你机器的IP，面向服务的路由了，给你选一个可用的出来，
      path: /spring-cloud-article/**
      #这里一定要是你Eureka注册中心的服务的名称，是所以这里配置serviceId因为跟eureka结合了，如果单独使用zuul,那么就必须写自己机器的IP了，
      url: http://${config.host:127.0.0.1}:${config.port:1003}
      #serviceId: spring-cloud-article

#日志配置
logging.level.ROOT: INFO
logging.level.org.springframework.web: INFO
logging.level.cn.com.waterelephant: INFO
# 日志路径
logging.file: /jason/logs/zuul/${spring.application.name}.log
# 控制台的日志模式
logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} - [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] - %msg%n'
# 日志记录模式文件
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] - [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] - %-5level %logger{36} - %msg%n'


